name: Feature Request
description: Got Something to Spice Up MiruTV?
title: "[Spice]: "
labels: ["feature_request"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to see?
      placeholder: Boku No Pico? Yeah, no.
    validations:
      required: true
  items:
    attributes: 
      label: By submitting, you'd agree to the following...
  - text: 'Checked the Issue tab that might relate to the suggested feature'
    checked: false
  - text: 'Checked the PR tab that might relate to the suggested feature'
    checked: false
  - type: markdown
    id: code
    attributes: 
      label: "If applicable, you can place the code here."